version: "3"

services:
  pokemon_manager:
    container_name: pokemon_manager
    build:
      context: .
    ports:
      - 8010:8000
    depends_on:
      - mysql
    networks:
      - pokemon_db

  mysql:
    container_name: pokemon_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'pokemon_manager'
      MYSQL_USER: "pokemon"
      MYSQL_PASSWORD: "pokemon"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: 'always'
    networks:
      - pokemon_db

networks:
  pokemon_db:
    driver: bridge